// papers_data.js
// Stores the specific question data for 2024/2025 series

// Initialize the global object if it doesn't exist
if (typeof paperData === 'undefined') {
    var paperData = {};
}

Object.assign(paperData, {
    /* 2025 SERIES */
    '2025_on_31': { title: "Pedro's Perfect Pies (PPP)", pdf: "9609_w25_in_31.pdf", questions: [ { n:'1', m:8, t:'Analyse two likely impacts on PPP of the changing external influences.', l:'150-225'}, { n:'2', m:8, t:'Analyse two benefits to PPP of using quality assurance.', l:'150-225'}, { n:'3(a)', m:2, t:'Using Table 1.3, calculate the payback period for PPP\'s new machine.'}, { n:'3(b)', m:2, t:'Using Table 1.3, calculate the ARR for PPP\'s new machine.'}, { n:'3(c)', m:12, t:'Evaluate whether PPP should invest in the new machine.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the monthly revenue from the sales of the classic pie after the price increase.'}, { n:'4(b)', m:12, t:'Evaluate the usefulness to PPP of elasticity measures.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the importance of emotional intelligence to Pedro\'s leadership.', l:'250-350'} ] },
    '2025_on_32': { title: "Komate Tropical Juice (KTJ)", pdf: "9609_w25_in_32.pdf", questions: [ { n:'1', m:8, t:'Analyse one advantage and one disadvantage to KTJ of delegation.', l:'150-225'}, { n:'2', m:8, t:'Analyse two impacts on KTJ of its commitment to CSR.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the payback period of the country C location.'}, { n:'3(b)', m:2, t:'Calculate the ARR of the country D location.'}, { n:'3(c)', m:12, t:'Evaluate which location KTJ should choose for its new factory.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the four period centred moving average for Quarter 1 2025.'}, { n:'4(b)', m:12, t:'Evaluate the usefulness of time series analysis to KTJ.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the likely impact on KTJ of fluctuations in the exchange rate.', l:'250-350'} ] },
    '2025_on_33': { title: "Lithium Battery Metals (LBM)", pdf: "9609_w25_in_33.pdf", questions: [ { n:'1', m:8, t:'Analyse two advantages to the government of country G from nationalisation.', l:'150-225'}, { n:'2', m:8, t:'Analyse one benefit and one limitation of sales forecasting to LBM.', l:'150-225'}, { n:'3(a)', m:2, t:'Using Table 1.1, calculate the payback period.'}, { n:'3(b)', m:2, t:'Using Table 1.1, calculate the NPV over six years discounted at 8%.'}, { n:'3(c)', m:12, t:'Evaluate LBM\'s decision to go ahead with the hot water mine.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate total float for activity C and minimum project duration.'}, { n:'4(b)', m:12, t:'Evaluate the importance of CPA to the success of the hard rock mine.', l:'250-350'}, { n:'5', m:12, t:'Evaluate LBM\'s decision to use two different approaches to HRM.', l:'250-350'} ] },
    '2025_mj_31': { title: "Wisdom Shoes (WS)", pdf: "9609_s25_in_31.pdf", questions: [ { n:'1', m:8, t:'Analyse two advantages to WS of using an environmental audit.', l:'150-225'}, { n:'2', m:8, t:'Analyse two benefits to WS of Enterprise Resource Planning (ERP).', l:'150-225'}, { n:'3(a)', m:2, t:'Refer to Table 1.4. Calculate the change in dividend yield.'}, { n:'3(b)', m:2, t:'Refer to Table 1.4. Calculate the change in P/E ratio.'}, { n:'3(c)', m:12, t:'Evaluate the likely impact on WS shareholders of the proposed changes.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the inventory turnover ratio.'}, { n:'4(b)', m:12, t:'Evaluate the usefulness of ratio analysis to WS directors.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the importance of environmental targets to WS success.', l:'250-350'} ] },
    '2025_mj_32': { title: "Pura AI Robots (PAIR)", pdf: "9609_s25_in_32.pdf", questions: [ { n:'1', m:8, t:'Analyse two benefits to PAIR of contingency planning.', l:'150-225'}, { n:'2', m:8, t:'Analyse two likely causes of the failure of the battery supplier.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the capacity utilisation for 2025.'}, { n:'3(b)', m:2, t:'Calculate the increase in profit margin.'}, { n:'3(c)', m:12, t:'Evaluate the likely impact on PAIR of the decision to increase investment in R&D.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the total float for the critical path.'}, { n:'4(b)', m:12, t:'Evaluate the usefulness of Critical Path Analysis (CPA) to PAIR.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the extent to which PAIRs future success depends on external influences.', l:'250-350'} ] },
    '2025_mj_33': { title: "We Care Products (WCP)", pdf: "9609_s25_in_33.pdf", questions: [ { n:'1', m:8, t:'Analyse two ways the external influences referred to in lines 8-12 may impact on WCP.', l:'150-225'}, { n:'2', m:8, t:'Analyse two benefits to WCP of its social objectives.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the labour turnover rate at GC.'}, { n:'3(b)', m:2, t:'Calculate the cost per unit.'}, { n:'3(c)', m:12, t:'Evaluate whether Aldin should change the HRM approach at GC.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the marketing budget variance.'}, { n:'4(b)', m:12, t:'Evaluate the effectiveness of WCP’s marketing strategy.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the likely impact on WCP of the takeover of GC.', l:'250-350'} ] },
    '2025_fm_32': { title: "Iyipada (IPA)", pdf: "9609_m25_in_32.pdf", questions: [ { n:'1', m:8, t:'Analyse one advantage and one disadvantage to IPA of changing employment contracts.', l:'150-225'}, { n:'2', m:8, t:'Analyse two methods to improve IPA\'s liquidity.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate, for 2024, IPA\'s market share.'}, { n:'3(b)', m:2, t:'Calculate, for 2025, the expected percentage market growth.'}, { n:'3(c)', m:12, t:'Evaluate the Marketing Director\'s proposed changes to IPA\'s marketing mix.', l:'250-350'}, { n:'4(a)', m:2, t:'Complete nodes 5 and 6 on the network diagram.'}, { n:'4(b)', m:2, t:'Calculate the total float for Activity F.'}, { n:'4(c)', m:12, t:'Evaluate the benefit to IPA of Critical Path Analysis (CPA).', l:'250-350'}, { n:'5', m:12, t:'Evaluate the most likely impact on IPA of the fiscal and monetary policy changes.', l:'250-350'} ] },

    /* 2024 SERIES */
    '2024_on_31': { title: "TopoChoc Enterprises (TC)", pdf: "9609_w24_in_31.pdf", questions: [ { n:'1', m:8, t:'Analyse two benefits to TC of marketing planning for the new range of chocolate bars.', l:'150-225'}, { n:'2', m:8, t:'Analyse two advantages to TC of setting SMART business objectives.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the current ratio for 2023.'}, { n:'3(b)', m:2, t:'Calculate the acid test ratio for 2023.'}, { n:'3(c)', m:12, t:'Evaluate whether the directors should worry about TCs liquidity.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the contribution of one chocolate bar.'}, { n:'4(b)', m:12, t:'Evaluate the proposal to produce chocolate bars.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the importance of Total Quality Management (TQM) to TC.', l:'250-350'} ] },
    '2024_on_32': { title: "Habesha Clean Cooking (HCC)", pdf: "9609_w24_in_32.pdf", questions: [ { n:'1', m:8, t:'Analyse two impacts on HCC of the increase in competition in country E.', l:'150-225'}, { n:'2', m:8, t:'Analyse two advantages to HCC of being a social enterprise.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the capacity utilisation for the Wonder Stove in 2023.'}, { n:'3(b)', m:2, t:'Calculate the increase in profit if production is outsourced.'}, { n:'3(c)', m:12, t:'Evaluate the decision to outsource production of the Wonder Stove.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the EST and LFT for activity F.'}, { n:'4(b)', m:12, t:'Evaluate the usefulness of Critical Path Analysis (CPA) to HCC.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the importance of business planning to the success of HCCs expansion into country K.', l:'250-350'} ] },
    '2024_on_33': { title: "Australasia Fitness Factory (AFF)", pdf: "9609_w24_in_33.pdf", questions: [ { n:'1', m:8, t:'Analyse two threats to AFF from changes in its external environment.', l:'150-225'}, { n:'2', m:8, t:'Analyse one advantage and one disadvantage to AFF of being a public limited company.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the return on capital employed (ROCE) for 2023.'}, { n:'3(b)', m:2, t:'Calculate the gearing ratio for 2023.'}, { n:'3(c)', m:12, t:'Evaluate the likely impact on AFF shareholders of the new share issue.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the dividend yield for 2022.'}, { n:'4(b)', m:12, t:'Evaluate the usefulness of ratio analysis to AFFs directors.', l:'250-350'}, { n:'5', m:12, t:'Evaluate whether TQM is the best way to solve customer complaint problems.', l:'250-350'} ] },
    '2024_mj_31': { title: "Gordy Building Supplies (GBS)", pdf: "9609_s24_in_31.pdf", questions: [ { n:'1', m:8, t:'Analyse two advantages to GBS of using flexible part-time employment contracts.', l:'150-225'}, { n:'2', m:8, t:'Analyse two disadvantages to GBS of its proposed communication process innovation.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the gearing ratio.'}, { n:'3(b)', m:2, t:'Calculate the return on capital employed (ROCE).'}, { n:'3(c)', m:12, t:'Evaluate the usefulness of ratio analysis to GBS’s directors.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the total float for activity C.'}, { n:'4(b)', m:12, t:'Evaluate the usefulness of Critical Path Analysis (CPA) to GBS.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the extent to which corporate social responsibility (CSR) should influence GBS’s decision to expand into new land.', l:'250-350'} ] },
    '2024_mj_32': { title: "Soymai Farms (SF)", pdf: "9609_s24_in_32.pdf", questions: [ { n:'1', m:8, t:'Analyse two advantages to SF of using flexible employment contracts.', l:'150-225'}, { n:'2', m:8, t:'Analyse two problems SF may experience when implementing total quality management (TQM).', l:'150-225'}, { n:'3(a)', m:2, t:'Refer to Table 1.1. Calculate the sales volume variation for Quarter 1 2023.'}, { n:'3(b)', m:2, t:'Refer to Table 1.1. Calculate the centred quarterly moving average for Quarter 2 2023.'}, { n:'3(c)', m:12, t:'Evaluate the usefulness of sales forecasting to SF.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the current capacity utilisation of the factory.'}, { n:'4(b)', m:12, t:'Evaluate the decision to outsource production of Sosoy Ice Cream.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the impact on SF of country B becoming a member of the NFTA international trading agreement.', l:'250-350'} ] },
    '2024_mj_33': { title: "Sunil's Clothing Company (SCC)", pdf: "9609_s24_in_33.pdf", questions: [ { n:'1', m:8, t:'Analyse two impacts on SCC of the changing external influences in country Z.', l:'150-225'}, { n:'2', m:8, t:'Analyse two disadvantages to SCC of the proposed new factory.', l:'150-225'}, { n:'3(a)', m:2, t:'Calculate the promotional elasticity of demand.'}, { n:'3(b)', m:2, t:'Calculate the price elasticity of demand.'}, { n:'3(c)', m:12, t:'Evaluate the usefulness of elasticity data to SCC.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the total float for activity B.'}, { n:'4(b)', m:12, t:'Evaluate the importance of Critical Path Analysis (CPA) to the success of the new factory.', l:'250-350'}, { n:'5', m:12, t:'Evaluate whether Sunil should use a soft or hard approach to human resource management.', l:'250-350'} ] },
    '2024_fm_32': { title: "Clean Delivery (CD)", pdf: "9609_m24_in_32.pdf", questions: [ { n:'1', m:8, t:'Analyse two benefits to CD resulting from internal economies of scale.', l:'150-225'}, { n:'2', m:8, t:'Analyse two advantages to CD of changing to a geographical organisational structure.', l:'150-225'}, { n:'3(a)', m:2, t:'Refer to Table 1.1. Calculate the Price Earnings (P/E) ratio for 2024.'}, { n:'3(b)', m:2, t:'Refer to Table 1.1. Calculate the Return on Capital Employed (ROCE) for 2024.'}, { n:'3(c)', m:12, t:'Evaluate the usefulness of ratio analysis to CD’s directors.', l:'250-350'}, { n:'4(a)', m:4, t:'Calculate the difference in capacity utilisation between 2022 and 2023.'}, { n:'4(b)', m:12, t:'Evaluate the importance of research and development (R&D) to CD’s future success.', l:'250-350'}, { n:'5', m:12, t:'Evaluate the impact on CD of the appreciation of country K’s exchange rate.', l:'250-350'} ] }
});